### ISSUE TITLE
gminer bugs after some switching

### ISSUE THREAD

**Issue by Gulio** [angelbbs/NiceHashMinerLegacy#51] opened 2019-02-07 00:49 UTC
After I mine some time with all algos enabled gminer bugs out (it constantly closes and reopens without starting mining).

The error in log that begins this process is:
[2019-02-07 01:31:10] [INFO] [GMiner] System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at NiceHashMiner.Miners.GMiner.KillMinerBase(String exeName) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\GMiner.cs:line 164

The algos that were switched at that time were those:
[2019-02-07 01:31:13] [INFO] [MiningSession] Stop Mining: { GPU#2 }: GrinCuckaroo29, { GPU#1, GPU#3 }: Beam, 
[2019-02-07 01:31:13] [INFO] [MiningSession] Now Mining : { GPU#1, GPU#2 }: GrinCuckaroo29, { GPU#3 }: Beam, 

Both Beam and Grin are using gminer. NicehashMinerLegacy tries to open 2 gminers to mine but there is another gminer that wasn't properly closed before and it opens constantly (even after I stop mining on nicehashminer). So all in all 3 gminers are trying to launch and they are trying to use the same gpus so they close each other in infinite loop.

I have tried already launching nicehashminer as administrator and made gminer run with watchdog disabled using extra launch parameters but had no success - it still bugs after some time of mining and switching.

**Comment by angelbbs** [comment] 2019-02-07 04:11
one of cards froze, so miner did not close

**Comment by nomemega** [comment] 2019-02-07 04:21
I solved the problem in my own way, I launch two versions of NiceHashMinerLegacy with different configurations of cards

**Comment by Gulio** [comment] 2019-02-07 09:51
> I solved the problem in my own way, I launch two versions of NiceHashMinerLegacy with different configurations of cards in the program

Actually it makes everything worse. 3 different NiceHashMinersLegacy often get current speeds from wrong windows and often when 1 miner tries to change algo all gminers close creating similar bug.

In few hours I will try to create 3 copies of NiceHashMinerLegacy instead of launching 3 times same copy with different config, maybe that is a problem.

**Comment by nomemega** [comment] 2019-02-07 09:54
The configuration is the same but the number of cards is different, an example is in one copy 1 card and in another 3

**Comment by nomemega** [comment] 2019-02-07 09:56
![ktu](https://user-images.githubusercontent.com/34583991/52403429-c0a6c180-2ad7-11e9-87d6-83f173b52812.png)

**Comment by angelbbs** [comment] 2019-02-07 10:05
@Gulio problem is in some of card

**Comment by Gulio** [comment] 2019-02-07 22:34
@nomemega thanks for tips but unfortunately theose do not work for me

@angelbbs i decreased memory overclock by 25Mhz, it is working for 3 hours now, will check tomorrow morning (in about 8-10 hours) but for now everything seems fine

**Comment by Gulio** [comment] 2019-02-08 11:46
@angelbbs still crashing even after reverting overclock to factory settings, do you know what the problem might be?

**Comment by Gulio** [comment] 2019-02-10 10:56
For the last 2 days I ran official nicehashminerlegacy and haven't had this issue with gminer

**Comment by Joshwaa2010** [comment] 2019-02-13 11:54
I had this same issue happening on one of my 1080ti's.  Turns out that I had to redo the TIM on the GPU die and replace the pads on the memory now the card is rock solid again. Generally if you start having weird issues it is due to overclock or cooling.

**Comment by davidhonasan** [comment] 2019-06-30 03:13
@angelbbs i also had this some kind of issue. you could easily reproduce this if you had 2 instances of gminer opened under 1 NHML, try closing 1 of the instance, then bug happens. it seems NHML want to closes both of instances or wrong GPU enumeration or something?

**Closed** 2019-11-16 23:39 UTC
